# Welcome to Jekyll!

# Website settings
title: CodeDiaries
description: Code Diaries - Blog
keywords: blog,Codediaries,github,gh-pages
#baseurl: https://codediaries.github.io # if you have suburl as homepage like '/homepage', please change it to '/homepage' and your repo's name should be 'homepage'
#baseurl: http://127.0.0.1:4000 # if you have suburl as homepage like '/homepage', please change it to '/homepage' and your repo's name should be 'homepage'
#url: https://codediaries.github.io  # url should be changed to 'http://www.jack003.com/homepage' as before
#url: http://127.0.0.1:4000
logo: /static/assets/img/logo.png
img_path: /static/assets/img/blog  # url should be changed to '/homepage/static/assets/img/blog' as before

# author -- index page "about me" section
author:  # change following line to your infomation.
  name: Kishan Rajdev  # Be used at blog posts' author.
  first_name: Kishan  # Be used at index page about me section.
  last_name: Rajdev  # Be used at index page about me section.
  cv: http://cv.jack003.com  # A online CV can be printed as PDF, leave blank if you don't have now
  email: kishanrajdev047@gmail.com  # Leave blank if you don't have now
  facebook_username: kishanrajdev  # Leave blank if you don't have now
  github_username: codediaries  # Leave blank if you don't have now
  linkedin_url: https://in.linkedin.com/in/kishan-rajdev-03593a55  # Leave blank if you don't have now
  avatar: /static/assets/img/landing/avatar.jpg  # upload your avatar at directory and edit it.
  skill_icon1:
    - name: icon-apache
    - name: fa-linux
  skill_icon2:
    - name: fa-linux
    - name: icon-apache
  desc:

# comment
disqus:  # if you wanna comment feature, go to https://disqus.com/ to get your configuration; if not, comment following two lines.
 # name: jalpc
 # public_key: tj2MPaNlHMONwTH5bGDNSXyaBpW7q282MeUzh5CwcjJerNhK8Kxk3aWo7IckzTX7

# analytics
## google analytics
ga:  # if you wanna this feature, go to https://www.google.com/analytics/ to get your configuration; if not, comment following line.
  # id:

## growingIO
gio:  # if you wanna this feature, go to https://www.growingio.com/ to get your configuration; if not, comment following line.
  # id:

## donation
# donation: on  # type 'on'/'off' to choice display donation button at post page or not


# Build settings
encoding: utf-8

# other settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
